defaults:
  - pooling: mean
  - _self_

_target_: fs_grl.pl_modules.distance_metric_learning.DistanceMetricLearning


optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

model:
  _target_: fs_grl.modules.baselines.adaptive_protonet.AdaptivePrototypicalNetwork
  feature_dim: ???
  num_classes: ???
  metric_scaling_factor: 7.5
  num_attention_heads: 1
  attention_dropout: 0.5

  loss_weights:
    classification_loss: 1
    latent_mixup_reg: 0.5
    intraclass_var_reg: 0.0
    adaptive_reg: 0.1

  num_classes_per_episode: ${nn.data.train_episode_hparams.num_classes_per_episode}

  embedder:
    _target_: fs_grl.modules.graph_embedder.GraphEmbedder
    pooling: ${nn.model.pooling}
    feature_dim: ???

    node_embedder:
      _target_: fs_grl.modules.node_embedder.NodeEmbedder
      feature_dim: ???
      hidden_dim: 64
      embedding_dim: 64
      num_convs: 2
      dropout_rate: 0.
      do_preprocess: false
      batch_norm: graph
      num_preproc_mlp_layers: 1
      num_postproc_mlp_layers: 2
      num_gin_mlp_layers: 2
      jump_mode: cat
      non_linearity:
        _target_: torch.nn.ReLU
