_target_: fs_grl.pl_modules.fully_graphical.FullyGraphical

optimizer:
  _target_: torch.optim.Adam
  lr: 5e-5

model:
  _target_: fs_grl.modules.fully_graphical_module.FullyGraphicalModule
  feature_dim: ???
  num_classes: ???
  margin: 0.5
  plot_graphs: false

  embedder:
    _target_: fs_grl.modules.node_embedder.NodeEmbedder
    feature_dim: ???
    num_mlp_layers: 2
    embedding_dim: 32
    hidden_dim: 32
    num_convs: 5
    dropout_rate: 0.6
    do_preprocess: false
