_target_: fs_grl.pl_modules.distance_metric_learning.DistanceMetricLearning

optimizer:
  _target_: torch.optim.Adam

model:
  _target_: fs_grl.modules.baselines.gnn_embedding_mlp.GNNEmbeddingMLP
  feature_dim: ???
  num_classes: ???
  margin: 0.5

  similarity_network:
    _target_: fs_grl.modules.mlp.MLP
    num_layers: 2
    input_dim: ???
    output_dim: 1
    hidden_dim: ???
    non_linearity: tanh

  embedder:
    _target_: fs_grl.modules.gnn_embedder.GNNEmbedder
    feature_dim: ???
    num_mlp_layers: 2
    embedding_dim: 64
    hidden_dim: 64
    num_convs: 2
    dropout_rate: 0
    do_preprocess: false
    pooling: sum
