_target_: fs_grl.pl_modules.dml_baseline.DMLBaseline

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5

model:
  _target_: fs_grl.modules.gnn_embedding_l2.GNNEmbeddingL2
  feature_dim: ???
  num_classes: ???
  margin: 0.5

  embedder:
    _target_: fs_grl.modules.gnn_embedder.GNNEmbedder
    feature_dim: ???
    num_mlp_layers: 2
    embedding_dim: 64
    hidden_dim: 64
    num_convs: 2
    dropout_rate: 0
