defaults:
  - kernel_method: graphlet
  - _self_

_target_: fs_grl.custom_pipelines.graph_kernel.graph_kernel_module.GraphKernel

node_labels_tag: attributes

classifier:
  _target_: sklearn.svm.SVC
  kernel: precomputed
