defaults:
  - pooling: mean
  - _self_

_target_: fs_grl.pl_modules.maml.MAMLModel
num_inner_steps: 5

outer_optimizer:
  _target_: torch.optim.Adam
  lr: 0.001 #0.01

inner_optimizer:
  _target_: torch.optim.SGD
  lr: 0.01

use_lr_scheduler: False

model:
  _target_: fs_grl.modules.architectures.gnn_mlp.GNN_MLP

  embedder:
    _target_: fs_grl.modules.components.graph_embedder.GraphEmbedder
    pooling: ${nn.model.pooling}
    feature_dim: ???

    node_embedder:
      _target_: fs_grl.modules.components.node_embedder.NodeEmbedder
      feature_dim: ???
      embedding_dim: 64
      hidden_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
      num_convs: 2
      dropout_rate: 0.0
      do_preprocess: false
      conv_norm: torch_geometric.nn.GraphNorm
      postproc_mlp_norm: torch.nn.LayerNorm
      num_preproc_mlp_layers: 1
      num_postproc_mlp_layers: 2
      num_gin_mlp_layers: 2
      jump_mode: cat
      non_linearity:
        _target_: torch.nn.ReLU

  classifier:
    _target_: fs_grl.modules.components.mlp.MLP
    num_layers: 2
    input_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
    output_dim: ??
    hidden_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
    non_linearity:
      _target_: torch.nn.ReLU
