defaults:
  - _self_
  - pooling: mean
  - conv_type: gin

_target_: fs_grl.pl_modules.distance_metric_learning.DistanceMetricLearning

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3

model:
  _target_: fs_grl.modules.architectures.proto_tadam.ProtoTADAM
  feature_dim: ???
  num_classes: ???
  metric_scaling_factor: 7.5
  gamma_0_init: 0.0
  beta_0_init: 1.0
  supports_aggregation: 'mean'

  loss_weights:
    classification_loss: 1
    latent_mixup_reg: 0.6
    intraclass_var_reg: 0.0
    film_reg: 0.8

  num_classes_per_episode: ${nn.data.episode_hparams.train.num_classes_per_episode}

  embedder:
    _target_: fs_grl.modules.components.graph_embedder.GraphEmbedder
    pooling: ${nn.model.pooling}
    feature_dim: ???

    node_embedder:
      _target_: fs_grl.modules.components.node_embedder.NodeEmbedder
      feature_dim: ???
      embedding_dim: 64
      hidden_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
      num_convs: 2
      dropout_rate: 0.5
      do_preprocess: false
      conv_norm: torch_geometric.nn.GraphNorm
      postproc_mlp_norm: torch.nn.LayerNorm
      num_preproc_mlp_layers: 1
      num_postproc_mlp_layers: 2
      num_gin_mlp_layers: 1
      jump_mode: cat
      conv_type: ${nn.model.conv_type}
      non_linearity:
        _target_: torch.nn.ReLU
