_target_: fs_grl.pl_modules.transfer_learning_source.TransferLearningSource

classifier_num_mlp_layers: 2

optimizer:
  _target_: torch.optim.Adam

embedder:
  _target_: fs_grl.modules.gnn_embedder.GNNEmbedder
  feature_dim: ???
  num_mlp_layers: 2
  embedding_dim: 64
  hidden_dim: 64
