seed_index: 0
deterministic: False

trainer:
  fast_dev_run: False
  gpus: 1
  precision: 32
  max_epochs: 100
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 10.0
  val_check_interval: 1.0
  log_every_n_steps: 1
  deterministic: ${train.deterministic}

logging:
  upload:
    run_files: true
    source: true

  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: ${core.project_name}
    entity: gladia
    log_model: ${..upload.run_files}
    mode: 'online'
    tags: ${core.tags}
