# Consider the appropriate datamodule when switching model
# distance metric learning --> GraphMetaDataModule
# transfer learning --> GraphTransferDataModule
# CHECK num_classes_per_episode when changing dataset
defaults:
  - model/gnn_embedding_cosine

data:
  _target_: fs_grl.data.datamodule.GraphMetaDataModule

  dataset_name: TRIANGLES
  data_features_to_consider: both
  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}
  classes_split_path: ${nn.data.data_dir}/classes_split.json

  train_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 15
    num_classes_per_episode: 3
    num_supports_per_class: 10

  val_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 5
    num_classes_per_episode: 2
    num_supports_per_class: 5

  test_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 15
    num_classes_per_episode: 3
    num_supports_per_class: 10

  num_train_episodes: 2000
  num_test_episodes: 500
  support_ratio: 0.8

  separated_query_support: false
  query_support_split_path: null
  train_ratio: 0.9

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 16
    val: 16
    test: 16
