
defaults:
  - _self_
  - data: triangles
  - model: prototypical_network

data:
  _target_: fs_grl.data.datamodule.GraphMetaDataModule

  dataset_name: ???
  feature_params:
    features_to_consider:
      - degree
#      - tags
#      - num_cycles
#      - pos_enc

    max_considered_cycle_len: 4
    num_pos_encs: 1

  add_artificial_nodes: ${oc.select:nn.model.add_artificial_nodes, false}
  artificial_node_features: zeros # zeros, ones, mean
  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}
  classes_split_path: ${nn.data.data_dir}/classes_split.json
  prototypes_path: ${nn.data.data_dir}/prototypes.pt
  scaling_factor_path: ${nn.data.data_dir}/scaling_factor.pt
  best_model_path: ${nn.data.data_dir}/best_model.ckpt.zip
  curriculum_learning: false
  max_difficult_step: 3000
  plot_graphs: false

  num_train_episodes: 2000
  num_val_episodes: 500
  num_test_episodes: 5000
  support_ratio: 0.8

  separated_query_support: false
  query_support_split_path: null
  train_ratio: 0.80

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 32
    val: 32
    test: 32
