# when changing model:
#   - change corresponding datamodule
#       - distance metric learning --> GraphMetaDataModule
#       - transfer learning --> GraphTransferDataModule
#   - change max_epochs and patience accordingly to the convergence time of the model

# when changing dataset:
#   - CHECK num_classes_per_episode
#   - NEVER use both on TRIANGLES, as tags are the same as degree, other datasets must still be tried

defaults:
  - _self_
  - model: gnn_embedding_cosine
  - data: r52

data:
  _target_: fs_grl.data.datamodule.GraphMetaDataModule

  dataset_name: ???
  feature_params:
    features_to_consider:
      - degree
      - num_cycles
    max_considered_cycle_len: 3

  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}
  classes_split_path: ${nn.data.data_dir}/classes_split.json
  prototypes_path: ${nn.data.data_dir}/prototypes.pt
  best_model_path: ${nn.data.data_dir}/best_model.ckpt.zip
  curriculum_learning: false
  max_difficult_step: 10000

  train_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 15
    num_classes_per_episode: 3
    num_supports_per_class: 10

  val_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 5
    num_classes_per_episode: 3
    num_supports_per_class: 5

  test_episode_hparams:
    _target_: fs_grl.data.episode.EpisodeHParams
    num_queries_per_class: 15
    num_classes_per_episode: 3
    num_supports_per_class: 10

  num_train_episodes: 2000
  num_test_episodes: 500
  support_ratio: 0.8

  separated_query_support: false
  query_support_split_path: null
  train_ratio: 0.9

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 16
    val: 16
    test: 16
