defaults:
  - _self_
  - data: tox21
  - model: tadam

data:
  _target_: fs_grl.data.datamodule.episodic_datamodule.GraphEpisodicDataModule

  dataset_name: ???
  feature_params:
    features_to_consider: # possibilities: degree, tags, num_cycles, pos_enc
      - degree
      - tags

    max_considered_cycle_len: 4
    num_pos_encs: 1

  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}
  classes_split_path: ${nn.data.data_dir}/classes_split.json

  num_episodes_per_epoch:
    train: 2000
    val: 500
    test: 1000

  train_ratio: 0.80

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 32
    val: 32
    test: 1
