defaults:
  - _self_
  - data: reddit
  - model: gsm


data:
  _target_: fs_grl.gsm.datamodule.GSMDataModule #fs_grl.data.datamodule.GraphMetaDataModule

  dataset_name: ???
  feature_params:
    features_to_consider:
      - degree
      - tags

    max_considered_cycle_len: 4
    num_pos_encs: 1

  data_dir: ${oc.env:PROJECT_ROOT}/data/${nn.data.dataset_name}
  classes_split_path: ${nn.data.data_dir}/classes_split.json
  spectral_prototypes_path: ${nn.data.data_dir}/spectral_prototypes_indices.json
  best_model_path: ${nn.data.data_dir}/best_model.ckpt.zip
  num_clusters:
    train: 2

  num_train_episodes: 2000
  num_val_episodes: 500
  num_test_episodes: 1000
  support_ratio: 0.8

  separated_query_support: false
  query_support_split_path: null
  train_ratio: 0.80

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 64
    val: 64
    test: 1 # extremely important, otherwise model will see more than K samples for each class
