_target_: torch_geometric.nn.GINConv
nn:
  _target_: fs_grl.modules.components.mlp.MLP
  num_layers: 1
  input_dim: ??
  output_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
  hidden_dim: ${nn.model.model.embedder.node_embedder.embedding_dim}
  norm: ${nn.model.model.embedder.node_embedder.conv_norm}
  non_linearity: ${nn.model.model.embedder.node_embedder.non_linearity}
